### ISSUE TITLE
Build Failed "UITextAlignmentLeft" is deprecated

### ISSUE THREAD

**Issue by corecryptics** [macmade/FileSystem#1]
Trying to get this app on my phone when I keep getting the error 
     
    'UITextAlignmentLeft' is deprecated: first deprecated in iOS 6.0.  
    FSFileListTableViewCell.m
    'UITextAlighnmentLeft' has been explicitly marked deprecated here.
Really would like to know how others have got past this.  I'm trying to run it on an iPhone 7 Plus running 10.3.2.  Any help?

**Comment by macmade** [comment]
Well, this app is no longer maintained, and was originally developed for iOS 2...

That being said, Google is your friend here:  
https://developer.apple.com/documentation/uikit/uitextalignment/uitextalignmentleft

As mentioned in Apple's documentation, `UITextAlignmentLeft` has been replaced by `NSTextAlignmentLeft`.
